apiVersion: apps/v1
kind: Deployment
metadata:
  # Specifies the name of the Deployment as "myapp".
  name: myapp

# The spec section defines the desired state of the Deployment.
spec:
  # Specifies the labels that are used to identify the pods targeted by this Deployment.
  selector:
    # Specifies that the Deployment should manage pods with the label "app: myapp".
    matchLabels:
      app: myapp
  # Specifies the desired number of replica pods
  replicas: 4
  # Specifies the pod template used to create new pods.
  template:
    metadata:
      # Specifies the labels for the pods created by this template.
      labels:
        app: myapp

    # Specifies the specification of the pod.
    spec:
      # Specifies the containers within the pod.
      containers:
      # Specifies the name of the container as "myapp".
      - name: myapp
        # Specifies the container image to be used for the "myapp" container.
        image: nanajanashia/argocd-app:1.2
        ports:
        # Specifies that the container exposes port 8080.
        - containerPort: 8080
