apiVersion: v1
kind: Service
metadata:
  # Specifies the name of the Service as "myapp-service".
  name: myapp-service

# The spec section defines the desired state of the Service.
spec:
  # Specifies the labels that the Service will use to select which pods will be part of this service.
  selector:
    # Specifies that the Service should route traffic to pods with the label "app: myapp".
    app: myapp
  ports:
    # Specifies the port on which the Service will listen for incoming traffic.
  - port: 8080
    # Specifies the protocol used for the port, which is TCP in this case.
    protocol: TCP
    # Specifies the target port on the pods to which the incoming traffic will be forwarded. This aligns with the port the pods are listening on.
    targetPort: 8080
  
