# It specifies the version of the Argo CD API that should be used to interpret the following configuration.
apiVersion: argoproj.io/v1alpha1

# Specifies the type of Kubernetes resource being defined, which in this case is an Argo CD Application.
kind: Application

metadata:
  # Specifies the name of the Argo CD Application as "myapp-argo-application".
  name: myapp-argo-application
  # Specifies the namespace in which the Argo CD Application should be created,
  namespace: argocd

# The spec section defines the desired state of the Argo CD Application.
spec:
  project: default

# Specifies the source of the application code and configuration.
  source:
    # Specifies the Git repository URL where the application code and configuration are stored.
    repoURL: https://github.com/Rama-Jamal/ArgoCD
    # Specifies the Git branch, tag, or commit to use. In this case, it uses the latest commit on the default branch (usually "master" or "main") as indicated by "HEAD".
    targetRevision: main
    # Specifies the directory within the Git repository where the application configuration is located.
    path: ArgoCD/dev

# Specifies the target Kubernetes cluster where the application will be deployed.
  destination: 
    # Specifies the Kubernetes cluster's API server URL.
    server: https://kubernetes.default.svc
    # Specifies the Kubernetes namespace where the application will be deployed.
    namespace: myapp
  
  # Specifies the synchronization policy for the Argo CD Application.
  syncPolicy:
    # Additional synchronization options. In this case, it includes "CreateNamespace=true," indicating that if the specified namespace does not exist, Argo CD should create it during synchronization.
    syncOptions:
    - CreateNamespace=true
    # Configuration for automated synchronization.
    automated:
      # Indicates whether the application should be automatically healed or corrected if it deviates from the desired state.
      selfHeal: true
      # Indicates whether to remove resources that are no longer declared in the application configuration during synchronization.
      prune: true